### ISSUE TITLE
jenkins --host http://jenkins_url:8080/ --username user.name --password api_token  jobs

### ISSUE THREAD

**Issue by shashankkoppar** [LD250/jenkins-cli-python#25]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/jenkins", line 11, in <module>
    load_entry_point('jenkins-cli==0.1.2', 'console_scripts', 'jenkins')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jenkins_cli-0.1.2-py3.6.egg/jenkins_cli/__init__.py", line 66, in main
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jenkins_cli-0.1.2-py3.6.egg/jenkins_cli/cli.py", line 90, in __init__
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jenkins_cli-0.1.2-py3.6.egg/jenkins_cli/cli.py", line 102, in auth
TypeError: __init__() takes from 2 to 4 positional arguments but 5 were given

Please help debugging

**Comment by LD250** [comment]
I think something wrong with args count.

Could you please print out `args` from line 61 in `jenkins-cli-python/jenkins_cli/__init__.py`?

**Comment by ShashanKK123** [comment]
@LD250 how do I print args, all I am doing is running this command in my terminal:
$jenkins --host http://jenkins_url:8080/ --username user.name --password api_token jobs
And then I get that error. 
Maybe it is some installation error too. I am trying to reinstall it and check.

**Comment by shashankkoppar** [comment]
I see it was the problem with 
pip 9.0.1 from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (python 3.6). 
It is working fine with  pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)

**Comment by LD250** [comment]
It's tested only on python 2.7 and 3.5. So there might be a problem with 3.6.

Should you fix a bug, please make a PR. PR's are always welcome!

**Comment by shashankkoppar** [comment]
Sure,and  this command doesn't get jobs if the job is located inside nested folder structure! 
Is there way i can get jobs which are present inside nested folders under any view?

**Comment by LD250** [comment]
No such feature in this release. But this can be done. You are welcome to create a pr.

You can check `python-jenkins` module for this feature.
